VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes
QMK_SETTINGS = yes
# EXTRAFLAGS += -flto

AUTO_SHIFT_ENABLE   = yes
TAP_DANCE_ENABLE    = yes
RETRO_TAPPING_ENABLE = yes
RETRO_SHIFT_ENABLE  = yes
t

RGBLIGHT_ENABLE     = no
RGB_MATRIX_ENABLE   = no # Can't have RGBLIGHT and RGB_MATRIX at the same time.
MOUSEKEY_ENABLE     = no
OLED_ENABLE         = no
OLED_DRIVER         = SSD1306

COMBO_ENABLE        = no
CONSOLE_ENABLE = no
NKRO_ENABLE = yes
SPLIT_KEYBOARD = yes
KEY_LOCK_ENABLE = yes

